### ISSUE TITLE
Admin UI does not run

### ISSUE THREAD

**Issue by p2** [smart-classic/smart_ui_server#6]
There must be an IQ-filter for the admin_ui app, because I can't get it to run. :)

After copying `settings.py.default`, adapting the settings and adding `APP_HOME`, the settings are okay, but then when I try to run the app I get:

```
cd smart_ui_server/admin_ui
python manage.py runserver 0.0.0.0:7003
Error: Could not import settings 'admin_ui.settings' (Is it on sys.path? Does it have syntax errors?): No module named settings
```

The settings.py file is there and `python settings.py` does not produce any errors. Am I doing something wrong?

Two remarks to settings.py.default:
- `APP_HOME` is missing and should just be set to `os.path.dirname(__file__)`, if not removed at all (I would happily fix that in .default if I knew it would run...)
- What does the setting `REPLACE_STRING` at the very top refer to?

**Comment by nschwertner** [comment]
Yes, you are right. Somehow the APP_HOME setting didn't end up in settings.py.default, while it should have been there. I updated the template and the readme accordingly.

The reason why Django cannot find the settings.py module is that it needs the following environment var:
DJANGO_SETTINGS_MODULE=settings

I updated the readme with the environment exports. The changes are in this commit:
https://github.com/chb/smart_ui_server/commit/7a9759abfb2b946d0c2a4762416c13d5648e6d70

**Comment by p2** [comment]
Thanks, saw the update, but after pulling and adjusting settings.py I'm still having trouble:

```
smart_ui_server $ cd admin_ui/
admin_ui $ export PYTHONPATH=.:..
admin_ui $ export DJANGO_SETTINGS_MODULE=settings
admin_ui $ python manage.py runserver 0.0.0.0:7003
Error: Could not import settings 'admin_ui.settings' (Is it on sys.path?): No module named settings
admin_ui $ python settings.py
admin_ui $ 
```

As a thought, maybe it would be worthwhile to spin out the admin UI as a separate repo, not nested in the UI server? We did that for Indivo.

**Comment by nschwertner** [comment]
Hmm... it works on my end. Let me see if I can replicate this issue and get back to you.

**Comment by p2** [comment]
Don't waste too much time on this! If you show me your settings.py and how you start it I can track it down myself.

**Comment by nschwertner** [comment]
I did try to replicate you experience from a vanilla clone from GitHUB, but I couldn't. It works just fine for me with the environment exports. I will send you my settings.py over e-mail.

**Comment by p2** [comment]
Thanks, I got your settings. Mine look the same (with the expected changes), but still the same error. Might it be a Django issue? I'm running 1.3.1 because Indivo doesn't yet run under 1.4.

I'll try some more, but it's of minor importance as I'll just use some other app's credentials for now.

On a sidenote, what about spinning it out into its own repo, outside of UI server?

**Comment by nschwertner** [comment]
That could be it. I am running Django 1.4. If you get a chance, try running it with Django 1.4 and let me know if it makes any difference.

**Comment by p2** [comment]
Updated to 1.4 and now SMART doesn't like me any more, even after nuking the database and even cloning the server again:

```
python manage.py validate
Error: One or more models did not validate:
admin.logentry: 'user' has a relation with model <class 'django.contrib.auth.models.User'>,
    which has either not been installed or is abstract.
```

Investigating...

**Comment by nschwertner** [comment]
Hmm... I am not sure if SMART runs under django 1.4. All of our servers (the public sandboxes and the VMs) run django 1.3. I think I will try upgrading a VM to see what will happen.

**Comment by nschwertner** [comment]
Oh... and with regards to the Admin UI app, I run it locally on my machine with django 1.4. However, I haven't tried running SMART directly on my machine (otside a VM)... Investigating as well

**Comment by p2** [comment]
Ah, wait, so you're only running the admin UI under 1.4, but not the servers? Oh okay; I'm running it all on the same machine, so I'll downgrade again.

The install directions say **Django 1.3+**, so I thought 1.4 is fine. But as I said, Indivo also doesn't like Django 1.4. And I'm starting not to like Django at all... ;)

**Comment by nschwertner** [comment]
Interesting... Upgrading to django 1.4 on a VM broke SMART as well. So, I guess we are not yet django 1.4 compatible.

**Comment by p2** [comment]
Back on 1.3.1, everything's fine again. I'll just not touch the admin UI for now, but since it's in the same repo as the UI server and I'm doing some refactoring there, can I ask you to try not to do too much work outside admin UI? Will make merging a lot easier I guess. :)

And I might update the indivo_client_py, maybe it's indeed a good idea to spin the admin_ui out with its own copy of the client_py.

**Comment by nschwertner** [comment]
Ok, I just tried the admin UI app with django 1.3 and got the same result as you:

Error: Could not import settings 'admin_ui.settings' (Is it on sys.path?): No module named settings

So it is definitely related to the django version. I will follow up on it, but won't be this week.

No worries about the code changes, just spin out a new branch out of the dev branch and hack away.

**Comment by p2** [comment]
Ok, thanks for confirming. I don't need the admin UI, so do as you please. And no need to fork off `dev`, I have my own branch, I was just thinking of preventing too many conflicts when we re-merge. :)

**Comment by nschwertner** [comment]
No worries. The admin UI is a self-contained mini-app. I am not planning on touching anything else in the UI server in the short run. I will make sure to let you know if there are any fixes to the admin UI.

**Comment by jmandel** [comment]
Should be fixed by:
https://github.com/chb/smart_ui_server/commit/2af893c1d85ad9fd8512bab20c793bf3fd3255ee
